FROM node:20.12.2-slim as build-stage
WORKDIR /app
COPY ./ui/package*.json ./
RUN npm install
COPY ./ui .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./nginx_ui/nginx.conf /etc/nginx/nginx.conf
