export const urls = {
    login: import.meta.env.VITE_LOGIN_URL,
    logout: import.meta.env.VITE_LOGOUT_URL,
    register: import.meta.env.VITE_REGISTER_URL,
    fetchUserUrl: import.meta.env.VITE_FETCH_USER_URL,
    setTokenUrl: import.meta.env.VITE_SET_TOKEN_URL,
    regCheckEmail: import.meta.env.VITE_REG_CHECK_EMAIL,
    regCheckUsername: import.meta.env.VITE_REG_CHECK_USERNAME,
    regConfirmationCode: import.meta.env.VITE_REG_CONFIRMATION_CODE,
    getConfirmationCode: import.meta.env.VITE_GET_CONFIRMATION_CODE,
    changeEmail: import.meta.env.VITE_CHANGE_EMAIL,
    changePass: import.meta.env.VITE_CHANGE_PASS,
    checkUsernameEmail: import.meta.env.VITE_CHECK_USERNAME_EMAIL,
    checkCode: import.meta.env.VITE_CHECK_CODE,
    restorePass: import.meta.env.VITE_RESTORE_PASS,
}