# Generated by Django 4.2 on 2025-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
        migrations.AlterModelOptions(
            name='functionality',
            options={'verbose_name': 'Функционал', 'verbose_name_plural': 'Функционал'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='filter',
            name='code',
            field=models.CharField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='full_text',
            field=models.TextField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(verbose_name='Заголовок'),
        ),
    ]
